---
- name: Fix Amazon cloud-init drain bamage
  hosts: all
  vars:
    ciFile: /etc/cloud/cloud.cfg
  tasks:
    - name: Make sure hostname will be preserved
      lineinfile:
        dest: "{{ciFile}}"
        line: "preserve_hostname: 1"
        insertafter: "^ssh_pwauth:"
      notify: reboot
    - name: Set hostname
      copy:
        dest: /etc/hostname
        content: "{{inventory_hostname}}"
      notify: reboot

  handlers:
    - name: reboot
      shell: reboot
      ignore_errors: true
      async: 1
      poll: 0
...