---
- name: Install first IPA server
  hosts: masters
  vars:
    serverPackages:
      - ipa-server
      - ipa-server-dns
      - firewalld
    ipaDomain:
      name: example.net
      realm: EXAMPLE.NET
      DMpw: MyeJv8Wjbf1LinKJ
      adminPw: s6IbWEi0Ggv4nJEX
    ipaServices:
      - http
      - https
      - ssh
      - kerberos
      - kpasswd
      - ldap
      - ldaps
      - ntp
      - dns
  tasks:
    - name: Update all packages
      yum:
        pkg: "*"
        state: latest
    - name: Install Server Packages
      yum:
        pkg: "{{item}}"
        state: latest
      with_items: "{{serverPackages}}"
    - name: Start firewalld
      service:
        name: firewalld
        state: started
        enabled: true
    - name: Configure firewalld
      firewalld:
        service: "{{item}}"
        immediate: true
        permanent: true
        state: enabled
      with_items: "{{ipaServices}}"
    - block:
        - name: Configure hostname in /etc/hosts
          lineinfile:
            dest: /etc/hosts
            insertafter: EOF
            line: "{{ansible_default_ipv4.address}} {{inventory_hostname}}"
        - name: Configure first IPA master
          command: "ipa-server-install --mkhomedir -U >
          -r {{ipaDomain.realm}} -n {{ipaDomain.name}} >
          -p {{ipaDomain.DMpw}} -a {{ipaDomain.adminPw}} >
          --ip-address={{ansible_default_ipv4.address}} >
          --setup-dns --forwarder=8.8.8.8 --forwarder=8.8.4.4 >
          --no-host-dns --hostname={{inventory_hostname}}"
      rescue:
        - name: Undo failed installation
          command: ipa-server-install --uninstall -U
        
...