---
- name: Install first IPA server
  hosts: ipaServers
  vars:
    ipaDomain:
      name: example.net
      realm: EXAMPLE.NET
      DMpw: MyeJv8Wjbf1LinKJ
      adminPw: s6IbWEi0Ggv4nJEX
    ipaServices:
      - http
      - https
      - ssh
      - kerberos
      - kpasswd
      - ldap
      - ldaps
      - ntp
      - dns
    ipaStateFile: /var/lib/ipa/sysrestore/sysrestore.state
  tasks:
    - name: Load distro-specific package lists
      include_vars: roles/ipaSystem/vars/{{ansible_distribution}}-packages.yml
    - name: Update all packages
      yum:
        pkg: "*"
        state: latest
    - block:
        - name: Yum Install Server Packages
          yum:
            pkg: "{{item}}"
            state: latest
          with_items: "{{serverPackages}}"
      rescue:
        - name: DNF Install Server Packages
          dnf:
            pkg: "{{item}}"
            state: latest
          with_items: "{{serverPackages}}"
    - name: Start firewalld
      service:
        name: firewalld
        state: started
        enabled: true
    - name: Configure firewalld
      firewalld:
        service: "{{item}}"
        immediate: true
        permanent: true
        state: enabled
      with_items: "{{ipaServices}}"
    - name: Configure hostname in /etc/hosts
      lineinfile:
        dest: /etc/hosts
        insertafter: EOF
        line: "{{ansible_default_ipv4.address}} {{inventory_hostname}}"
    - name: Check for previous install
      stat:
        path: "{{ipaStateFile}}"
      register: ipaState
    - block:
        - name: Configure first IPA master
          when: ipaState.stat.exists == false and inventory_hostname in group['masters']
          command: "ipa-server-install --mkhomedir -U >
          -r {{ipaDomain.realm}} -n {{ipaDomain.name}} >
          -p {{ipaDomain.DMpw}} -a {{ipaDomain.adminPw}} >
          --ip-address={{ansible_default_ipv4.address}} >
          --setup-dns --forwarder=8.8.8.8 --forwarder=8.8.4.4 >
          --no-host-dns --hostname={{inventory_hostname}}"
          async: 1800
          poll: 30
      rescue:
        - name: Undo failed installation
          command: ipa-server-install --uninstall -U
        - name: Remove old IPA state file
          file:
            dest: "{{ipaStateFile}}"
            state: absent
        
...